stages:
  - deploy

deploy-dev:
  stage: deploy
  tags:
    - personal-front-melani
  only:
    - Melani
  script:
    - docker build -t personal-front:deployment .
    - docker-compose down
    - docker container rm personal-front
    - docker image rm personal-front:latest
    - docker tag personal-front:deployment personal-front:latest
    - docker rmi personal-front:deployment
    - docker-compose up -d
