stages:
  - deploy

deploy-dev:
  stage: deploy
  tags:
    - personal-front-melani
  only:
    - development
  script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - docker build -t personal-front:deployment .
    - docker-compose down
    - docker image rm personal-front:latest || true
    - docker tag personal-front:deployment personal-front:latest
    - docker image rm personal-front:deployment
    - docker-compose up -d
