version: '3'

services:
    web:
        image: personal-front
        container_name: personal-front
        restart: always
        build:
            context: .
        ports:
            - 9035:3000
        environment:
            - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
            - NEXT_PUBLIC_API_SIGERH=$NEXT_PUBLIC_API_SIGERH
